### ISSUE TITLE
Authenticate button doesnt work on Netbeans 11 

### ISSUE THREAD

**Issue by MichaelHabib** [massimozappino/tagmycode-netbeans#1]
The Authenticate button doesn't work on Netbeans 11 running on Ubuntu 18 LTS .

**Comment by massimozappino** [comment]
I installed TagMyCode Plugin for Netbeans version 2.2.1 on Netbeans 11 (Ubuntu 18.04 LTS) and authentication worked correctly opening Google Chrome.

`Product Version: Apache NetBeans IDE 11.0 (Build incubator-netbeans-release-404-on-20190319)
Java: 1.8.0_121; Java HotSpot(TM) 64-Bit Server VM 25.121-b13
Runtime: Java(TM) SE Runtime Environment 1.8.0_121-b13
System: Linux version 4.15.0-47-generic running on amd64; UTF-8; en_US (nb)`

Can you provide more details?

**Comment by MichaelHabib** [comment]
Now it works !
I don't know what was the issue, but in that time I have restarted both NetBeans & FF so that could be the solution to my issue !.
Anyways, thanks for the response, I;ll close the issue now.
